import archiver from "archiver";
import { createWriteStream } from "node:fs";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { finished } from "node:stream/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { PublicationBook } from "./model.js";

export interface BuildResult { epubPath:string; sha256:string; size:number; }
export interface PublishResult extends BuildResult { releaseUrl:string; downloadUrl:string; }

export async function buildPublication(book:PublicationBook):Promise<BuildResult>{
  const root=path.resolve(".build",book.id,"epub"); const metaInf=path.join(root,"META-INF"); const oebps=path.join(root,"OEBPS"); const textDir=path.join(oebps,"text"); const stylesDir=path.join(oebps,"styles"); const imagesDir=path.join(oebps,"images");
  await rm(root,{recursive:true,force:true}); await Promise.all([mkdir(metaInf,{recursive:true}),mkdir(textDir,{recursive:true}),mkdir(stylesDir,{recursive:true}),mkdir(imagesDir,{recursive:true})]);
  await writeFile(path.join(root,"mimetype"),"application/epub+zip");
  await writeFile(path.join(metaInf,"container.xml"),`<?xml version="1.0" encoding="UTF-8"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/package.opf" media-type="application/oebps-package+xml" /></rootfiles></container>`);
  await writeFile(path.join(stylesDir,"book.css"),css(book.profile));

  const hrefByMediaId:Record<string,string>={}; const assetItems:Array<{id:string;href:string;type:string}> = [];
  let assetIndex=0;
  for(const media of Object.values(book.media)){
    if(!["Image","Map"].includes(media.type))continue; const source=media.externalUrl??media.permanentUrl; if(!source)continue;
    const response=await fetch(source,{redirect:"follow"}); if(!response.ok)throw new Error(`Asset download failed ${response.status}: ${media.name}`);
    const bytes=Buffer.from(await response.arrayBuffer()); const type=(response.headers.get("content-type")??"image/jpeg").split(";")[0]; const ext=extFor(type,source); const file=`${safe(media.id)}${ext}`; await writeFile(path.join(imagesDir,file),bytes); const href=`images/${file}`; hrefByMediaId[media.id]=href; assetItems.push({id:`asset-${++assetIndex}`,href,type});
  }

  const pages:Array<{id:string;href:string;title:string;toc:boolean}> = [];
  for(const page of book.pages){const file=`${String(page.order).padStart(3,"0")}-${safe(page.id||page.name)}.xhtml`; const href=`text/${file}`; await writeFile(path.join(textDir,file),renderPage(book,page,hrefByMediaId)); pages.push({id:`page-${page.order}`,href,title:page.tocTitle||page.name,toc:page.showInTOC});}
  await writeFile(path.join(oebps,"nav.xhtml"),nav(book,pages));
  await writeFile(path.join(oebps,"package.opf"),opf(book,pages,assetItems,hrefByMediaId));

  const outDir=path.resolve("output"); await mkdir(outDir,{recursive:true}); const epubPath=path.join(outDir,`${book.id}-v${book.version}.epub`); const output=createWriteStream(epubPath); const archive=archiver("zip",{zlib:{level:9}}); archive.pipe(output); archive.file(path.join(root,"mimetype"),{name:"mimetype",store:true}); archive.directory(metaInf,"META-INF"); archive.directory(oebps,"OEBPS"); await archive.finalize(); await finished(output);
  const bytes=await readFile(epubPath); const sha256=createHash("sha256").update(bytes).digest("hex"); const info=await stat(epubPath); return{epubPath,sha256,size:info.size};
}

export async function publishPublication(book:PublicationBook):Promise<PublishResult>{
  const build=await buildPublication(book); const token=requiredEnv("GITHUB_TOKEN"); const repo=process.env.BOOKAPP_RELEASE_REPOSITORY?.trim()||"Equilibriumpress/bookapp-books"; const [owner,name]=repo.split("/"); const tag=`${book.id}-v${book.version}`;
  let release=await ghMaybe(`/repos/${owner}/${name}/releases/tags/${encodeURIComponent(tag)}`,token);
  if(!release) release=await gh(`/repos/${owner}/${name}/releases`,token,{method:"POST",body:JSON.stringify({tag_name:tag,name:`${book.title} v${book.version}`,body:`Bookapp publication for ${book.title}.`,draft:false,prerelease:false})});
  const fileName=path.basename(build.epubPath); const bytes=await readFile(build.epubPath); const existing=(release.assets??[]).find((a:any)=>a.name===fileName); if(existing) await gh(`/repos/${owner}/${name}/releases/assets/${existing.id}`,token,{method:"DELETE"});
  const uploadUrl=String(release.upload_url).replace("{?name,label}",""); const up=await fetch(`${uploadUrl}?name=${encodeURIComponent(fileName)}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/epub+zip","Content-Length":String(bytes.length)},body:bytes}); if(!up.ok)throw new Error(`GitHub release upload failed ${up.status}: ${await up.text()}`); const asset=await up.json() as any;
  await updateCatalog(owner,name,book,build,asset.browser_download_url,token); return{...build,releaseUrl:release.html_url,downloadUrl:asset.browser_download_url};
}

async function updateCatalog(owner:string,repo:string,book:PublicationBook,build:BuildResult,downloadUrl:string,token:string){const current=await ghMaybe(`/repos/${owner}/${repo}/contents/catalog.json?ref=main`,token);let catalog:any={schemaVersion:1,updatedAt:null,books:[]};let sha:string|undefined;if(current?.content){catalog=JSON.parse(Buffer.from(String(current.content).replaceAll("\n",""),"base64").toString("utf8"));sha=current.sha;}const next={id:book.id,title:book.title,subtitle:book.subtitle,author:book.author,language:book.language,version:book.version,profile:book.profile,downloadUrl,sha256:build.sha256,size:build.size,updatedAt:new Date().toISOString()};const books=(catalog.books??[]).filter((b:any)=>b.id!==book.id);books.push(next);books.sort((a:any,b:any)=>a.title.localeCompare(b.title));const body={schemaVersion:catalog.schemaVersion??1,updatedAt:new Date().toISOString(),books};await gh(`/repos/${owner}/${repo}/contents/catalog.json`,token,{method:"PUT",body:JSON.stringify({message:`Publish ${book.title} v${book.version}`,content:Buffer.from(JSON.stringify(body,null,2)+"\n").toString("base64"),branch:"main",...(sha?{sha}:{})})});}

function renderPage(book:PublicationBook,page:any,assets:Record<string,string>){const primary=page.primaryMediaId?assets[page.primaryMediaId]:undefined;const comps=page.componentIds.map((id:string)=>book.components[id]).filter(Boolean).sort((a:any,b:any)=>a.order-b.order);let body=`<section class="page template-${x(page.template)}">`;if(primary)body+=`<img class="page-photo" src="../${x(primary)}" alt="${x(book.media[page.primaryMediaId]?.altText||page.name)}" />`;body+=`<div class="page-copy">${page.eyebrow?`<p class="eyebrow">${h(page.eyebrow)}</p>`:""}${page.template==="cover"?`<h1>${h(page.name)}</h1>`:`<h2>${h(page.name)}</h2>`}${page.deck?`<p class="deck">${h(page.deck)}</p>`:""}${page.bodyHtml}`;for(const c of comps){const mediaId=c.mediaIds[0];const m=mediaId?book.media[mediaId]:undefined;const href=mediaId?assets[mediaId]:undefined;if(c.type==="image"&&href&&m)body+=`<figure><img src="../${x(href)}" alt="${x(m.altText)}" /><figcaption>${h(c.body||m.caption)}</figcaption></figure>`;else if(c.type==="map"&&href&&m)body+=`<figure class="map-figure"><img src="../${x(href)}" alt="${x(m.altText)}" /><figcaption>${h(c.body||m.caption)}</figcaption><p><a href="bookapp://map/${x(book.id)}/${x(m.id)}">Open interactive map</a></p></figure>`;else if(c.body)body+=`<p>${h(c.body)}</p>`;}body+=`</div></section>`;const viewport=book.profile==="fixed"?`<meta name="viewport" content="width=1200,height=1600" />`:`<meta name="viewport" content="width=device-width" />`;return`<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="${x(book.language)}" xml:lang="${x(book.language)}"><head><meta charset="utf-8" />${viewport}<title>${h(page.name)}</title><link rel="stylesheet" type="text/css" href="../styles/book.css" /></head><body>${body}</body></html>`;}
function nav(book:PublicationBook,pages:any[]){return`<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="${x(book.language)}"><head><meta charset="utf-8" /><title>Contents</title></head><body><nav epub:type="toc" id="toc"><h1>Contents</h1><ol>${pages.filter(p=>p.toc).map(p=>`<li><a href="${x(p.href)}">${h(p.title)}</a></li>`).join("")}</ol></nav></body></html>`;}
function opf(book:PublicationBook,pages:any[],assets:any[],hrefs:Record<string,string>){const modified=new Date().toISOString().replace(/\.\d{3}Z$/,"Z");const coverHref=book.coverMediaId?hrefs[book.coverMediaId]:undefined;return`<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" unique-identifier="pub-id" version="3.0" xml:lang="${x(book.language)}"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="pub-id">urn:bookapp:${x(book.id)}:v${book.version}</dc:identifier><dc:title>${h(book.title)}</dc:title><dc:creator>${h(book.author)}</dc:creator><dc:language>${x(book.language)}</dc:language><meta property="dcterms:modified">${modified}</meta><meta property="rendition:layout">${book.profile==="fixed"?"pre-paginated":"reflowable"}</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="style" href="styles/book.css" media-type="text/css"/>${pages.map(p=>`<item id="${p.id}" href="${x(p.href)}" media-type="application/xhtml+xml"/>`).join("")}${assets.map(a=>`<item id="${a.id}" href="${x(a.href)}" media-type="${x(a.type)}"${a.href===coverHref?' properties="cover-image"':''}/>`).join("")}</manifest><spine>${pages.map(p=>`<itemref idref="${p.id}"/>`).join("")}</spine></package>`;}
function css(profile:string){return`@page{margin:0}html,body{margin:0;padding:0;color:#201f1b;background:#f7f4ec;font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif}body{${profile==="fixed"?"width:1200px;height:1600px;overflow:hidden;":"max-width:46rem;margin:0 auto;"}}.page{box-sizing:border-box;min-height:100%;padding:7% 8%}.page-photo,figure img{width:100%;height:auto}.page-photo{max-height:58%;object-fit:cover}.eyebrow{font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;font-weight:700}h1,h2,h3{font-family:Georgia,"Times New Roman",serif;line-height:1.05}.deck{font-size:1.25rem;line-height:1.45;color:#555047}p{line-height:1.58}figcaption{font-size:.8rem;color:#625d54}a{color:inherit;text-decoration:underline}`;}
function extFor(type:string,source:string){const m:Record<string,string>={"image/jpeg":".jpg","image/png":".png","image/webp":".webp","image/gif":".gif","image/svg+xml":".svg"};return m[type]??path.extname(new URL(source).pathname)??".jpg";}function safe(v:string){return v.toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-|-$/g,"")||"page";}function h(v:string){return v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");}function x(v:string){return h(v).replaceAll('"',"&quot;");}function requiredEnv(n:string){const v=process.env[n]?.trim();if(!v)throw new Error(`${n} is required`);return v;}async function gh(pathName:string,token:string,init:RequestInit={}){const r=await fetch(`https://api.github.com${pathName}`,{...init,headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(init.headers??{})}});if(!r.ok)throw new Error(`GitHub ${r.status}: ${await r.text()}`);return r.status===204?null:r.json();}async function ghMaybe(pathName:string,token:string){const r=await fetch(`https://api.github.com${pathName}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"}});if(r.status===404)return undefined;if(!r.ok)throw new Error(`GitHub ${r.status}: ${await r.text()}`);return r.json();}
